// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit.

export const firebaseConfig = {
  apiKey: 'AIzaSyAGAdn6hT9fhaGqmqN5LpcUlWV3FW-rNTw',
  authDomain: 'studio-2526433000-2e931.firebaseapp.com',
  projectId: 'studio-2526433000-2e931',
  storageBucket: 'studio-2526433000-2e931.appspot.com',
  messagingSenderId: '548223774566',
  appId: '1:548223774566:web:16693942e42061dd6a22a7',
};
